# Generated by Django 5.2 on 2025-08-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]