# Generated by Django 4.2.23 on 2025-09-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailoring', '0005_alter_customer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='measurements',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
