# Generated by Django 4.2.23 on 2025-09-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailoring', '0006_alter_customer_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='down_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='down_payment_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='down_payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DOWN_PAYMENT_PAID', 'Down Payment Paid'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
