# Generated by Django 4.2.23 on 2025-09-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailoring', '0007_add_down_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accessories_preference',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
