# Generated by Django 5.2 on 2025-09-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailoring', '0009_task_approved_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PAID', 'Paid')], default='APPROVED', max_length=10),
        ),
    ]
