# Generated by Django 5.2.8 on 2025-11-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailoring', '0010_alter_commission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='garment_type',
            field=models.CharField(choices=[('BLOUSE', 'Blouse'), ('POLO', 'Polo'), ('PANTS', 'Pants'), ('SKIRT', 'Skirt'), ('DRESS', 'Dress'), ('JACKET', 'Jacket'), ('OTHERS', 'Others')], default='OTHERS', max_length=10),
        ),
    ]
