"""Remove accessories_preference field from Order model.

Generated by patching script.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etailoring', '0012_order_inventory_deducted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accessories_preference',
        ),
    ]
