# Generated by Django 5.2.8 on 2025-12-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailoring', '0014_increase_phone_number_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='accessory',
            name='applicable_garments',
            field=models.ManyToManyField(blank=True, to='etailoring.garmenttype'),
        ),
    ]
