"""
Comprehensive Tailor Performance Report Generator using ReportLab
"""
import os
import io
from datetime import datetime, timedelta
from decimal import Decimal
from django.conf import settings
from django.db.models import Count, Sum, Avg, Q
from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.platypus import Image as ReportLabImage
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.linecharts import HorizontalLineChart
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from io import BytesIO
import base64

from .models import Tailor, Task, Commission, Order


class TailorReportGenerator:
    """Generate comprehensive tailor performance reports"""
    
    def __init__(self, tailor, date_from=None, date_to=None, generated_by=None):
        self.tailor = tailor
        self.date_from = date_from or (timezone.now() - timedelta(days=365))
        self.date_to = date_to or timezone.now()
        self.generated_by = generated_by
        self.buffer = BytesIO()
        
        # Company branding colors
        self.primary_color = colors.Color(0.8, 0.4, 0.2)  # Warm brown/orange
        self.secondary_color = colors.Color(0.9, 0.7, 0.5)  # Light peach
        self.accent_color = colors.Color(0.2, 0.4, 0.6)  # Blue accent
        
    def generate_report(self):
        """Generate the complete tailor performance report"""
        # Create PDF document
        doc = SimpleDocTemplate(
            self.buffer,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        
        # Build story (content)
        story = []
        
        # Add header
        story.extend(self._create_header())
        story.append(Spacer(1, 20))
        
        # Add tailor information section
        story.extend(self._create_tailor_info_section())
        story.append(Spacer(1, 20))
        
        # Add commission summary
        story.extend(self._create_commission_summary())
        story.append(Spacer(1, 20))
        
        # Add task performance metrics
        story.extend(self._create_task_performance_section())
        story.append(Spacer(1, 20))
        
        # Add financial overview
        story.extend(self._create_financial_overview())
        story.append(Spacer(1, 20))
        
        # Add footer
        story.extend(self._create_footer())
        
        # Build PDF
        doc.build(story)
        
        # Get PDF data
        pdf_data = self.buffer.getvalue()
        self.buffer.close()
        
        return pdf_data
    
    def _create_header(self):
        """Create report header with company branding"""
        styles = getSampleStyleSheet()
        
        # Company header style
        header_style = ParagraphStyle(
            'CustomHeader',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=self.primary_color,
            alignment=TA_CENTER,
            spaceAfter=10
        )
        
        subtitle_style = ParagraphStyle(
            'CustomSubtitle',
            parent=styles['Normal'],
            fontSize=14,
            textColor=self.accent_color,
            alignment=TA_CENTER,
            spaceAfter=20
        )
        
        content = []
        
        # Company name and logo placeholder
        content.append(Paragraph("🧵 El Senior Dumingag Tailoring", header_style))
        content.append(Paragraph("Tailor Performance Report", subtitle_style))
        
        # Report metadata
        date_range = f"{self.date_from.strftime('%B %d, %Y')} - {self.date_to.strftime('%B %d, %Y')}"
        generated_date = timezone.now().strftime('%B %d, %Y at %I:%M %p')
        
        metadata_style = ParagraphStyle(
            'Metadata',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.grey,
            alignment=TA_CENTER
        )
        
        content.append(Paragraph(f"Report Period: {date_range}", metadata_style))
        content.append(Paragraph(f"Generated on: {generated_date}", metadata_style))
        if self.generated_by:
            content.append(Paragraph(f"Generated by: {self.generated_by.get_full_name()}", metadata_style))
        
        return content
    
    def _create_tailor_info_section(self):
        """Create tailor information section"""
        styles = getSampleStyleSheet()
        
        section_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=self.primary_color,
            spaceAfter=10
        )
        
        content = []
        content.append(Paragraph("👤 Tailor Information", section_style))
        
        # Tailor details table
        tailor_data = [
            ['Full Name:', self.tailor.user.get_full_name()],
            ['Email:', self.tailor.user.email],
            ['Phone:', getattr(self.tailor, 'phone', 'N/A')],
            ['Employee ID:', f"T{self.tailor.id:04d}"],
            ['Employment Start:', self.tailor.user.date_joined.strftime('%B %d, %Y')],
            ['Specialization:', getattr(self.tailor, 'specialization', 'General Tailoring')],
        ]
        
        tailor_table = Table(tailor_data, colWidths=[2*inch, 4*inch])
        tailor_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), self.secondary_color),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        
        content.append(tailor_table)
        
        return content

    def _create_task_performance_section(self):
        """Create task performance metrics section"""
        styles = getSampleStyleSheet()

        section_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=self.primary_color,
            spaceAfter=10
        )

        content = []
        content.append(Paragraph("📋 Task Performance Metrics", section_style))

        # Get task data
        tasks = Task.objects.filter(
            tailor=self.tailor,
            assigned_at__range=[self.date_from, self.date_to]
        )

        total_assigned = tasks.count()
        in_progress = tasks.filter(status='IN_PROGRESS').count()
        completed = tasks.filter(status='COMPLETED').count()
        approved = tasks.filter(status='APPROVED').count()

        completion_rate = ((completed + approved) / total_assigned * 100) if total_assigned > 0 else 0

        # Task performance table
        task_data = [
            ['Total Tasks Assigned:', str(total_assigned)],
            ['Tasks In Progress:', str(in_progress)],
            ['Tasks Completed:', str(completed)],
            ['Tasks Approved:', str(approved)],
            ['Completion Rate:', f"{completion_rate:.1f}%"],
        ]

        task_table = Table(task_data, colWidths=[3*inch, 2*inch])
        task_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), self.secondary_color),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))

        content.append(task_table)
        content.append(Spacer(1, 15))

        # Tasks by garment type
        garment_stats = tasks.values('order__garment_type').annotate(
            count=Count('id')
        ).order_by('-count')

        if garment_stats:
            content.append(Paragraph("Tasks by Garment Type:", styles['Heading3']))

            garment_data = [['Garment Type', 'Count', 'Percentage']]
            for stat in garment_stats:
                garment_type = stat['order__garment_type']
                count = stat['count']
                percentage = (count / total_assigned * 100) if total_assigned > 0 else 0
                garment_data.append([
                    garment_type.replace('_', ' ').title(),
                    str(count),
                    f"{percentage:.1f}%"
                ])

            garment_table = Table(garment_data, colWidths=[2*inch, 1*inch, 1*inch])
            garment_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.primary_color),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, self.secondary_color]),
            ]))

            content.append(garment_table)

        return content

    def _create_financial_overview(self):
        """Create financial overview section"""
        styles = getSampleStyleSheet()

        section_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=self.primary_color,
            spaceAfter=10
        )

        content = []
        content.append(Paragraph("📊 Financial Overview", section_style))

        # Get monthly earnings data
        commissions = Commission.objects.filter(
            tailor=self.tailor,
            created_at__range=[self.date_from, self.date_to]
        ).order_by('created_at')

        # Calculate monthly totals
        monthly_data = {}
        for commission in commissions:
            month_key = commission.created_at.strftime('%Y-%m')
            if month_key not in monthly_data:
                monthly_data[month_key] = {'paid': Decimal('0'), 'pending': Decimal('0')}

            if commission.status == 'PAID':
                monthly_data[month_key]['paid'] += commission.amount
            else:
                monthly_data[month_key]['pending'] += commission.amount

        if monthly_data:
            content.append(Paragraph("Monthly Earnings Breakdown:", styles['Heading3']))

            monthly_table_data = [['Month', 'Paid Earnings', 'Pending Earnings', 'Total']]
            total_paid_all = Decimal('0')
            total_pending_all = Decimal('0')

            for month_key in sorted(monthly_data.keys()):
                month_name = datetime.strptime(month_key, '%Y-%m').strftime('%B %Y')
                paid = monthly_data[month_key]['paid']
                pending = monthly_data[month_key]['pending']
                total = paid + pending

                total_paid_all += paid
                total_pending_all += pending

                monthly_table_data.append([
                    month_name,
                    f"₱{paid:,.2f}",
                    f"₱{pending:,.2f}",
                    f"₱{total:,.2f}"
                ])

            # Add totals row
            monthly_table_data.append([
                'TOTAL',
                f"₱{total_paid_all:,.2f}",
                f"₱{total_pending_all:,.2f}",
                f"₱{total_paid_all + total_pending_all:,.2f}"
            ])

            monthly_table = Table(monthly_table_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 1.5*inch])
            monthly_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.primary_color),
                ('BACKGROUND', (0, -1), (-1, -1), self.accent_color),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('TEXTCOLOR', (0, -1), (-1, -1), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
                ('FONTNAME', (0, 1), (-1, -2), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, self.secondary_color]),
            ]))

            content.append(monthly_table)

        return content

    def _create_footer(self):
        """Create report footer"""
        styles = getSampleStyleSheet()

        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=8,
            textColor=colors.grey,
            alignment=TA_CENTER
        )

        content = []
        content.append(Spacer(1, 30))
        content.append(Paragraph("This report is confidential and intended for authorized personnel only.", footer_style))
        content.append(Paragraph("El Senior Dumingag Tailoring - Professional Tailoring Services", footer_style))

        return content

    def get_filename(self):
        """Generate appropriate filename for the report"""
        tailor_name = self.tailor.user.get_full_name().replace(' ', '_')
        date_range = f"{self.date_from.strftime('%Y%m%d')}_to_{self.date_to.strftime('%Y%m%d')}"
        generated_date = timezone.now().strftime('%Y%m%d')

        return f"Tailor_Report_{tailor_name}_{date_range}_{generated_date}.pdf"
    
    def _create_commission_summary(self):
        """Create commission summary section"""
        styles = getSampleStyleSheet()
        
        section_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=self.primary_color,
            spaceAfter=10
        )
        
        content = []
        content.append(Paragraph("💰 Commission Summary", section_style))
        
        # Get commission data
        commissions = Commission.objects.filter(
            tailor=self.tailor,
            created_at__range=[self.date_from, self.date_to]
        )
        
        total_paid = commissions.filter(status='PAID').aggregate(Sum('amount'))['amount__sum'] or Decimal('0')
        total_pending = commissions.filter(status='APPROVED').aggregate(Sum('amount'))['amount__sum'] or Decimal('0')
        total_commissions = commissions.count()
        avg_commission = commissions.aggregate(Avg('amount'))['amount__avg'] or Decimal('0')
        
        # Commission summary table
        commission_data = [
            ['Total Paid Commissions:', f"₱{total_paid:,.2f}"],
            ['Pending Commissions:', f"₱{total_pending:,.2f}"],
            ['Total Commission Count:', str(total_commissions)],
            ['Average Commission:', f"₱{avg_commission:,.2f}"],
            ['Total Potential Earnings:', f"₱{total_paid + total_pending:,.2f}"],
        ]
        
        commission_table = Table(commission_data, colWidths=[3*inch, 2*inch])
        commission_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), self.secondary_color),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        
        content.append(commission_table)
        
        return content
